<body>
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card " style="background-color: #f5ede8;">
                    <div class=" card_logo">
                        <img src="../img/logo.png" class="card-img-top" alt="Imagem de Capa">
                    </div>
                    <div class="card-body">
                        <div class="container">
                            <div class="row">
                                <div class="col text-center">
                                    <h1 class="card-title ">Usuário cadastrado com sucesso!</h1>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col text-center">
                                    <a href="/" class="btn btn-primary">Faça o login agora!</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Adicione o link para o Bootstrap JS e o Popper.js, necessários para funcionalidades do Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>