<body>

    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class=" card_logo">
                        <img src="../img/logo.png" class="card-img-top" alt="Imagem de Capa">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Login</h5>
                        <form action="/autenticar" method="post">
                            <div class="form-group">
                                <label for="usuario">Email</label>
                                <input name='email' type="text" class="form-control" id="usuario" placeholder="Digite seu Email">
                            </div>
                            <div class="form-group">
                                <label for="senha">Senha</label>
                                <input name='senha' type="password" class="form-control" id="senha" placeholder="Digite sua senha">
                            </div>
                            <button type="submit" class="btn btn-primary mt-3">Logar</button>
                            <?php if ($this->view->login == 'erro') { ?>
                                <div class="row">
                                    <div class="col">
                                        <span class='text text-danger'>*Email ou senha inválidos</span>

                                    </div>
                                </div>
                            <?php } ?>
                        </form>
                        <div class="mt-3">
                            <p>Não tem uma conta? <a href="/registrar">Crie uma agora!</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Adicione o link para o Bootstrap JS e o Popper.js, necessários para funcionalidades do Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>