<div class="col-6 mx-auto mt-3">
    <h3>Editar post</h3>
    <form method="post" action='/editar?id=<?= $_GET['id'] ?>'>

        <div class="form-group">
            <label for="titulo"></label>
            <input value='<?= $this->view->detalhes['titulo'] ?>' name="titulo" class="form-control" type="text" id="titulo">
        </div>

        <div class="form-group">
            <label for="conteudo">Conteúdo</label>
            <textarea class="form-control" name="conteudo" id="conteudo"><?= $this->view->detalhes['conteudo'] ?></textarea>
        </div>

        <div class="form-group">
            <label for="categoria">Categoria</label>
            <select class="form-control" name="categoria" id="categoria">
                <option <?= $this->view->detalhes['categoria'] == 'trabalho' ? 'selected' : '' ?> value="trabalho">Trabalho</option>
                <option <?= $this->view->detalhes['categoria'] == 'tecnologia' ? 'selected' : '' ?> value="tecnologia">Tecnologia</option>
                <option <?= $this->view->detalhes['categoria'] == 'empreendedorismo' ? 'selected' : '' ?> value="empreendedorismo">Empreendedorismo</option>
            </select>
        </div>


        <div class="col mt-2 d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">Editar</button>
        </div>

    </form>
</div>