<div class="container">
    <div class="p-2 m-2 card">
        <div class="d-flex justify-content-between align-items-center">
            <h1><?= $this->view->detalhes['titulo'] ?> - <?= $this->view->detalhes['categoria'] ?></h1>
            <?php if ($_SESSION['id'] == $this->view->detalhes['id_autor']) { ?>
                <span>
                    <a class="btn btn-warning float-right" href="/editar_post?id=<?= $this->view->detalhes['id'] ?>">Editar</a>
                    <a class="btn btn-danger float-right" href="/excluir_post?id=<?= $this->view->detalhes['id'] ?>">Excluir</a>
                </span>
            <?php } ?>
        </div>

        <h6><?= $this->view->detalhes['data_atualizacao'] ?></h6>
        <small>Criado em: <?= $this->view->detalhes['data'] ?></small>
        <div class="card-body text-center">
            <p><?= $this->view->detalhes['conteudo'] ?></p>
        </div>
    </div>

    <h1>Comentários</h1>
    <a href="#" id="mostrarFormulario" class="btn btn-primary">Novo Comentário</a>
    <form action="/comentar" method="post" id="meuFormulario" style="display: none;">
        <div class="form-group">
            <input type="hidden" name="id_post" value="<?= $_GET['id'] ?>">
            <input type="hidden" name="id_usuario" value="<?= $_SESSION['id'] ?>">

            <label for="textoArea">Escreva o que você achou:</label>
            <textarea name="comentario" class="form-control" id="textoArea" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-success">Comentar</button>
    </form>

    <div class="p-2 m-2 card">
        <div class="d-flex justify-content-between align-items-center">
            <h6>Leandro - 20/08/2000</h6>
            <?php if ($_SESSION['id'] == $this->view->detalhes['id_autor']) { ?>
                <span>
                    <a class="btn btn-warning float-right" href="/editar_post?id=<?= $this->view->detalhes['id'] ?>">Editar</a>
                    <a class="btn btn-danger float-right" href="/excluir_post?id=<?= $this->view->detalhes['id'] ?>">Excluir</a>
                </span>
            <?php } ?>
        </div>

        <p>Meu belissimo comentário</p>
    </div>

</div>

<script>
    $(document).ready(function() {
        $("#mostrarFormulario").click(function(e) {
            e.preventDefault();
            $("#meuFormulario").toggle();
        });
    });
</script>