<div class="col-6 mx-auto mt-3">
    <h3>Novo post</h3>
    <form method="post" action='/postar'>

        <div class="form-group">
            <label for="titulo">Título</label>
            <input name="titulo" class="form-control" type="text" id="titulo">
        </div>

        <div class="form-group">
            <label for="conteudo">Conteúdo</label>
            <textarea class="form-control" name="conteudo" id="conteudo"></textarea>
        </div>

        <div class="form-group">
            <label for="categoria">Categoria</label>
            <select class="form-control" name="categoria" id="categoria">
                <option value="trabalho">Trabalho</option>
                <option value="tecnologia">Tecnologia</option>
                <option value="empreendedorismo">Empreendedorismo</option>
            </select>
        </div>


        <div class="col mt-2 d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">Postar</button>
        </div>

    </form>
</div>