<div class="col-6 mx-auto mt-3">
    <a class="btn btn-primary" href="/novo_post">Novo Post</a>

    <?php foreach ($this->view->posts as $id_posts => $post) { ?>
        <div class="card m-1 bg-light">
            <div class="card-body">
                <h4 class="card-title"><?= $post['titulo'] ?> - <?= $post['categoria'] ?></h4>
                <h5>Autor: <?= $post['nome_autor'] ?></h5>
                <h6 class="card-subtitle">Data de atualização: <?= $post['data_atualizacao'] ?> </h6>
                <small>Data de postagem: <?= $post['data'] ?></small>
                <div style="max-width: 5000px;">
                    <p style="
                    overflow: hidden; 
                    display: -webkit-box; 
                    -webkit-line-clamp: 3; 
                    -webkit-box-orient: vertical; 
                    text-overflow: ellipsis;" class="card-text" class="card-text"><?= $post['conteudo'] ?></p>
                </div>



                <div class="d-flex justify-content-between align-items-center">

                    <a href="/leia_mais?id=<?= $post['id'] ?>" class="mr-auto">Leia Mais</a>
                    <?php if ($_SESSION['id'] == $post['id_autor']) { ?>
                        <span>
                            <a class="btn btn-warning float-right" href="/editar_post?id=<?= $post['id'] ?>">Editar</a>
                            <a class="btn btn-danger float-right" href="/excluir_post?id=<?= $post['id'] ?>">Excluir</a>
                        </span>

                    <?php } ?>


                </div>



            </div>

        </div>

    <?php } ?>

</div>